require:
  - rubocop-performance
  - rubocop-rails

inherit_from:
  - https://raw.githubusercontent.com/carbonfive/c5-conventions/master/rubocop/rubocop.yml

AllCops:
  TargetRubyVersion: 2.6

Rails:
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false
